[project]
name = "odoo-addons-oca-repair"
version = "18.0.20250220.0"
dependencies = [
    "odoo-addon-repair_type==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
